CREATE TABLE user_tb(
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR NOT NULL UNIQUE,
    password VARCHAR NOT NULL,
    email VARCHAR NOT NULL,
    created_at TIMESTAMP
);

CREATE TABLE product_tb(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR NOT NULL UNIQUE,
    price INT NOT NULL,
    qty INT NOT NULL,
    created_at TIMESTAMP
);